test-all:
	cd fgg && make parser
	cd fg && make test-all
	cd fgg && make test-all
.PHONY: test-all

test-unit:
	cd fgg && make parser
	cd fg && make test-unit
	cd fgg && make test-unit
.PHONY: test-unit
