test-all:
	cd interpreters && make test-all
	cd monomorphisers/fgg2go && make test-all
.PHONY: test-all

test-unit:
	cd interpreters && make test-unit
	cd monomorphisers/fgg2go && make test-unit
.PHONY: test-unit

run-fg:
	cd interpreters/fg && make run
.PHONY: run-fg

run-fgg:
	cd interpreters/fgg && make run
.PHONY: run-fgg

run-monomo:
	cd monomorphisers/fgg2go && make run
.PHONY: run-monomo
