name: Build docs on GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/gh-pages.yml"

jobs:
  build-docs:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone reveal.js
        run: git clone https://github.com/hakimel/reveal.js.git public

      - name: Remove default reveal.js slides
        run: rm public/*.html

      - name: Copy presentation slides to GH pages directory
        run: |
          cp docs/3-presentation/dist/index.html public/presentation.html
          cp docs/3-presentation/presentation.md public/presentation.md

      - name: Set up TexLive
        run: sudo apt update && sudo apt install texlive-full

      - name: Set up Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Compile LaTeX report
        working-directory: docs/2-report
        run: make main.pdf

      - name: Copy report to GH pages directory
        run: cp docs/2-report/main.pdf public/report.pdf

      - name: Compile cycle detection summary
        working-directory: docs/4-cycle-detection-summary
        run: pdflatex -shell-escape summary

      - name: Copy cycle detection summary GH pages directory
        run: cp docs/4-cycle-detection-summary/summary.pdf public/cycle-detection-summary.pdf

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
